### ISSUE TITLE
Code de transaction pour le voyant lumineux est 03 ?

### ISSUE THREAD

**Issue by ArmandBriere** [guyfrancoeur/INF3135_A2019_TP#1]
L'affichage on nous parle de "Code de transaction pour le voyant lumineux est 03". Cette valeur de 03 correspond à quelque chose mais je n'arrive pas à comprendre ce que ce numéro représente !

**Comment by lachalex** [comment]
Chaque donnée envoyée au système est identifiée par un numéro qui permet de les différencier. C'est le premier chiffre de chaque ligne. 
01 - Cette donnée est un changement d'état de l'avion (De TARMAC à TAKEOFF par exemple)
02 - Cela signifie une lecture d'un capteur. Dans ce travail il n'y a que les capteurs d'angle de l'avion.
03 - C'est un signal destiné au tableau de bord. Dans ce travail il s'agit d'indiquer qu'un changement au voyant lumineux est nécessaire. C,est ce que votre programme doit afficher.
