### ISSUE TITLE
Premier affichage du programme ?

### ISSUE THREAD

**Issue by ArmandBriere** [guyfrancoeur/INF3135_A2019_TP#4]
Je cite `Au démarrage du système, le voyant lumineux devra être dans l'état GREEN`
Devons-nous juste considéré que le voyant est `GREEN` au départ ou devons-nous afficher :
`0 03 ANGLE GREEN` au tout début ?

**Comment by guyfrancoeur** [comment]
Allo,

voir #2 

GF
